# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filter_selection.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import sys


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(284, 219)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.radio_filter_Nl = QtWidgets.QRadioButton(Dialog)
        self.radio_filter_Nl.setObjectName("radio_filter_Nl")
        self.verticalLayout.addWidget(self.radio_filter_Nl)
        self.radio_filter_Lee = QtWidgets.QRadioButton(Dialog)
        self.radio_filter_Lee.setObjectName("radio_filter_Lee")
        self.verticalLayout.addWidget(self.radio_filter_Lee)
        #self.radio_filter_Lee_E = QtWidgets.QRadioButton(Dialog)
        #self.radio_filter_Lee_E.setObjectName("radio_filter_Lee_E")
        #self.verticalLayout.addWidget(self.radio_filter_Lee_E)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 2)
        self.Button_OK = QtWidgets.QPushButton(Dialog)
        self.Button_OK.setObjectName("Button_OK")
        self.gridLayout.addWidget(self.Button_OK, 1, 0, 1, 1)
        self.Button_cancle = QtWidgets.QPushButton(Dialog)
        self.Button_cancle.setObjectName("Button_cancle")
        self.gridLayout.addWidget(self.Button_cancle, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "滤波方式选择"))
        self.radio_filter_Nl.setText(_translate("Dialog", "NL滤波"))
        self.radio_filter_Lee.setText(_translate("Dialog", "Lee滤波"))
        #self.radio_filter_Lee_E.setText(_translate("Dialog", "增强Lee滤波（待完成）"))
        self.Button_cancle.setText(_translate("Dialog", "Cancle"))
        self.Button_OK.setText(_translate("Dialog", "OK"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QDialog()
    ui = Ui_Dialog()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())