# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filter_Lee.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import sys


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(238, 259)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_image = QtWidgets.QLabel(Dialog)
        self.label_image.setObjectName("label_image")
        self.gridLayout.addWidget(self.label_image, 0, 0, 1, 2)
        self.Btn_image_open = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(8)
        self.Btn_image_open.setFont(font)
        self.Btn_image_open.setObjectName("Btn_image_open")
        self.gridLayout.addWidget(self.Btn_image_open, 0, 3, 1, 1)
        self.text_image = QtWidgets.QTextEdit(Dialog)
        self.text_image.setObjectName("text_image")
        self.gridLayout.addWidget(self.text_image, 1, 0, 1, 4)
        self.label_filter_window = QtWidgets.QLabel(Dialog)
        self.label_filter_window.setObjectName("label_filter_window")
        self.gridLayout.addWidget(self.label_filter_window, 2, 0, 1, 1)
        self.line_path_output = QtWidgets.QLineEdit(Dialog)
        self.line_path_output.setObjectName("line_path_output")
        self.gridLayout.addWidget(self.line_path_output, 3, 1, 1, 3)
        self.Button_OK = QtWidgets.QPushButton(Dialog)
        self.Button_OK.setObjectName("Button_OK")
        self.gridLayout.addWidget(self.Button_OK, 6, 0, 1, 2)
        self.Button_cancle = QtWidgets.QPushButton(Dialog)
        self.Button_cancle.setObjectName("Button_cancle")
        self.gridLayout.addWidget(self.Button_cancle, 6, 2, 1, 2)
        self.label_path_output = QtWidgets.QLabel(Dialog)
        self.label_path_output.setObjectName("label_path_output")
        self.gridLayout.addWidget(self.label_path_output, 3, 0, 1, 1)
        self.line_filter_window = QtWidgets.QLineEdit(Dialog)
        self.line_filter_window.setObjectName("line_filter_window")
        self.gridLayout.addWidget(self.line_filter_window, 2, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "filter-Lee"))
        self.label_filter_window.setText(_translate("Dialog", "滤波窗口大小："))
        self.Button_OK.setText(_translate("Dialog", "OK"))
        self.Button_cancle.setText(_translate("Dialog", "Cancle"))
        self.Btn_image_open.setText(_translate("Dialog", "打开"))
        self.label_image.setText(_translate("Dialog", "待滤波影像"))
        self.label_path_output.setText(_translate("Dialog", "输出文件路径"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QDialog()
    ui = Ui_Dialog()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())