# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sample_selection_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import sys

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(273, 264)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_shp = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_shp.setObjectName("lineEdit_shp")
        self.gridLayout.addWidget(self.lineEdit_shp, 7, 0, 1, 1)
        self.radio_shp_SAR = QtWidgets.QRadioButton(Dialog)
        self.radio_shp_SAR.setObjectName("radio_shp_SAR")
        self.gridLayout.addWidget(self.radio_shp_SAR, 1, 0, 1, 1)
        self.radio_shp_manual = QtWidgets.QRadioButton(Dialog)
        self.radio_shp_manual.setObjectName("radio_shp_manual")
        self.gridLayout.addWidget(self.radio_shp_manual, 3, 0, 1, 1)
        #self.radio_shp_GF = QtWidgets.QRadioButton(Dialog)
        #self.radio_shp_GF.setObjectName("radio_shp_GF")
        #self.gridLayout.addWidget(self.radio_shp_GF, 2, 0, 1, 1)
        self.label_title = QtWidgets.QLabel(Dialog)
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_title.setObjectName("label_title")
        self.gridLayout.addWidget(self.label_title, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 7, 1, 1, 1)
        self.label_shp = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_shp.sizePolicy().hasHeightForWidth())
        self.label_shp.setSizePolicy(sizePolicy)
        self.label_shp.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_shp.setObjectName("label_shp")
        self.gridLayout.addWidget(self.label_shp, 4, 0, 1, 1)
        self.Button_OK = QtWidgets.QPushButton(Dialog)
        self.Button_OK.setMaximumSize(QtCore.QSize(80, 16777215))
        self.Button_OK.setObjectName("Button_OK")
        self.gridLayout.addWidget(self.Button_OK, 8, 0, 1, 1)
        self.Button_cancle = QtWidgets.QPushButton(Dialog)
        self.Button_cancle.setMaximumSize(QtCore.QSize(80, 16777215))
        self.Button_cancle.setObjectName("Button_cancle")
        self.gridLayout.addWidget(self.Button_cancle, 8, 1, 1, 1)

        self.label_shp.setEnabled(False)
        self.lineEdit_shp.setEnabled(False)
        self.pushButton.setEnabled(False)

        self.initUI() #xuhang add
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "样本选取"))
        self.radio_shp_SAR.setText(_translate("Dialog", "基于SAR平台选取样本"))
        self.radio_shp_manual.setText(_translate("Dialog", "用户输入样本"))
        # self.radio_shp_GF.setText(_translate("Dialog", "基于GF平台选取样本"))
        self.label_title.setText(_translate("Dialog", "样本输入方式："))
        self.pushButton.setText(_translate("Dialog", "打开"))
        self.label_shp.setText(_translate("Dialog", "  请选取样本文件（shp格式）："))
        self.Button_OK.setText(_translate("Dialog", "OK"))
        self.Button_cancle.setText(_translate("Dialog", "Cancle"))

    def initUI(self):
        self.radio_shp_SAR.setChecked(True)
        self.radio_shp_SAR.toggled.connect(self.btnClick)
        #self.radio_shp_GF.toggled.connect(self.btnClick)
        self.radio_shp_manual.toggled.connect(self.btnClick)

        self.pushButton.clicked.connect(self.Btn_path_click)

    #radio文件单击事件
    def btnClick(self, btnText):
        if self.radio_shp_manual.isChecked() == True:
            self.label_shp.setEnabled(True)
            self.lineEdit_shp.setEnabled(True)
            self.pushButton.setEnabled(True)

    #打开文件事件
    def Btn_path_click(self):
        print("用户选取shp文件")
        fileDir, filetype = QFileDialog.getOpenFileName(None, "选取矢量样本(*.shp)", "D:/workspace/","shp Files (*.shp);;All Files (*)")
        if fileDir != '':
            self.lineEdit_shp.setText(fileDir)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QDialog()
    ui = Ui_Dialog()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())